apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: ops
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-storage
  local:
    path: /opt/jenkins
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker01-k8
          - worker02-k8

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-storage
  namespace: ops
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pv-claim
  namespace: ops
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: jenkins-storage
  resources:
    requests:
      storage: 10Gi