apiVersion: v1
kind: PersistentVolume            
metadata:
  name: sonar-pv-data
  namespace: ops
spec:
  storageClassName: standard  
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:                       
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain 
