apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data
  namespace: ops
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 250Mi
