---
- name: Add k8s apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes

- name: Install k8s packages
  apt:
    name: "{{ item }}"
  loop: "{{ k8s_packages }}"

- name: Disable swap
  command: swapoff -a

- name: Ensure they can see bridge traffic
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  with_items:
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-ip6tables

- name: Destroy cluster before starting again
  command: kubeadm reset -f

- name: Initialize k8s cluster
  command: kubeadm init
  register: kubeadm_init_output

- name: Install pod network
  command: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Create .kube directory
  become: yes
  become_user: ubuntu
  file:
    path: $HOME/.kube
    state: directory
    mode: 0600

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu

#- name: Define control plane node isolation
#  command: kubectl taint nodes --all node-role.kubernetes.io/master-