---
- name: Download istioctl
  get_url:
    url: https://istio.io/downloadIstioctl
    dest: /home/ubuntu

- name: Install istioctl
  become: yes
  become_user: ubuntu
  command: "sh downloadIstioCtl.sh"

- name: Add istioctl to the path via .bashrc
  lineinfile: dest=/home/ubuntu/.bashrc line='export PATH=$PATH:$HOME/.istioctl/bin' insertafter='EOF' regexp='export PATH=\$PATH:$HOME/.istioctl/bin' state=present

- name: Install istio
  become: yes
  become_user: ubuntu
  command: "/home/ubuntu/.istioctl/bin/istioctl install --set profile=demo -y"

- name: Verify istio install 
  become: yes
  become_user: ubuntu
  command: "/home/ubuntu/.istioctl/bin/istioctl verify-install"

- name: Install grafana addon 
  become: yes
  become_user: ubuntu
  command: "kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.8/samples/addons/grafana.yaml"
  
- name: Install jaeger addon 
  become: yes
  become_user: ubuntu
  command: "kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.8/samples/addons/jaeger.yaml"

- name: Install prometheus addon 
  become: yes
  become_user: ubuntu
  command: "kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.8/samples/addons/prometheus.yaml"

- name: Install kiali addon 
  become: yes
  become_user: ubuntu
  command: "kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.8/samples/addons/kiali.yaml"