---
#- name: Create dev namespace
#  become: yes
#  become_user: ubuntu
#  command: "kubectl create ns dev"
#
#- name: Inject istio on dev namespace
#  become: yes
#  become_user: ubuntu
#  command: "kubectl label namespace dev istio-injection=enabled"
#
#- name: Create istio gateway for dev namespace 
#  become: yes
#  become_user: ubuntu
#  shell: 
#    cmd: | 
#      cat <<EOF | kubectl apply -f -
#      apiVersion: networking.istio.io/v1alpha3
#      kind: Gateway
#      metadata:
#        name: gateway
#        namespace: dev
#      spec:
#        servers: 
#          - port:
#              number: 80
#              name: http
#              protocol: HTTP
#            hosts:
#              - dev.deltacare.xyz
#            tls:
#              httpsRedirect: true
#          - port:
#              name: https
#              number: 443
#              protocol: HTTP
#            hosts:
#              - dev.deltacare.xyz
#      EOF
   
- name: Create virtual service for dev namespace
  become: yes
  become_user: ubuntu
  shell: 
    cmd: | 
      cat <<EOF | kubectl apply -f -
      apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      metadata:
        name: vs
        namespace: dev 
      spec:
        hosts:
          - dev.deltacare.xyz
        gateways:
          - gateway
        http:cxvcx
          - match:
              - uri:
                  exact: /api/v1/empresas
              - uri:
                  exact: /api/v1/empresas/
              - uri:
                  regex: '/api/v1/empresas/[0-9]+'
            name: api-empresa
            route:
              - destination:
                  host: api-empresa
                  port:
                    number: 8080
          - match:
              - uri:
                  exact: /api/v1/produtos
              - uri:
                  exact: /api/v1/produtos/
              - uri:
                  regex: '/api/v1/produtos/[0-9]+'
            name: api-produto
            route:
              - destination:
                  host: api-produto
                  port:
                    number: 8080
          - match:
              - uri:
                  exact: /api/v1/faturas
              - uri:
                  exact: /api/v1/faturas/
              - uri:
                  regex: '/api/v1/faturas/[0-9]+'
            name: api-fatura
            route:
              - destination:
                  host: api-fatura
                  port:
                    number: 8080
          - match:
              - uri:
                  exact: /api/v1/painel
              - uri:
                  exact: /api/v1/painel/
              - uri:
                  regex: '/api/v1/painel/[0-9]+'
            name: api-painel
            route:
              - destination:
                  host: api-painel
                  port:
                    number: 8080
          - match:
              - uri:
                  prefix: /api/v1/empresas/
            name: api-empresa-swagger
            rewrite:
              uri: /
            route:
              - destination:
                  host: api-empresa
                  port:
                    number: 8080
          - match:
              - uri:
                  prefix: /api/v1/produtos/
            name: api-produto-swagger
            rewrite:
              uri: /
            route:
              - destination:
                  host: api-produto
                  port:
                    number: 8080
          - match:
              - uri:
                  prefix: /api/v1/faturas/
            name: api-fatura-swagger
            rewrite:
              uri: /
            route:
              - destination:
                  host: api-fatura
                  port:
                    number: 8080
          - match:
              - uri:
                  prefix: /api/v1/painel/
            name: api-painel-swagger
            rewrite:
              uri: /
            route:
              - destination:
                  host: api-painel
                  port:
                    number: 8080
          - match:
              - uri:
                  prefix: /
            name: web
            route:
              - destination:
                  host: spa
                  port:
                    number: 80
      EOF