apiVersion: v1
kind: Namespace
metadata:
 name: dev
---
apiVersion: v1
kind: Namespace
metadata:
 name: hml
---
apiVersion: v1
kind: Namespace
metadata:
 name: prd
---
apiVersion: v1
kind: Namespace
metadata:
 name: ops
